Fix mousemove bug, ghost offset bug, and many others
cyclejs-community/cyclejs-sortable pull request #15
Opened 2017-06-17 23:12 UTC by ntilwalli

**Fix mousemove bug:** previously double-clicking an element left the mousemove stream active.
**Ghost offset bug:** The ghost was previously being shifted to the right and down in a non-intuitive way, now the ghost starts in the original place, 
**Bug requiring children if no handle option set:**  previously having an empty list and no `handle` option set caused a crash.  Now, the list does not react until there are two or more children
**Remove need for emitBetween**:  Use `endWhen`
**Use border-box:**  Added border-box to simple and horizontal examples to get rid of ghost rendering bigger than original element when clicked.
**Use relative position for parent css selectors:** This lib requires the parent elements to have a position set to anything other than `static`.  It can't be ensured in the code directly since we may overwrite the existing position class.  relative positioning has been added to simple and horizontal examples.
**Add code to implement `ghostClass` option:** this was not previously implemented, though the option existed in the `options`

2017-06-17 23:16 UTC, ntilwalli commented
This PR fixes https://github.com/cyclejs-community/cyclejs-sortable/pull/15

2017-06-17 23:30 UTC, jvanbruegge requested changes
I just had a quick look over it, thanks for the PR. I have to check it more thoroughly, this are mostly style comments

2017-06-17 23:30 UTC, jvanbruegge commented on examples/simple/css/main.css
> +  box-sizing: border-box;
can you indent with 4 spaces please?

2017-06-17 23:30 UTC, jvanbruegge commented on examples/simple/src/index.ts
> +    .compose(makeSortable<Stream<VNode>>(DOM, {ghostClass: '.ghost'}));
Please add spaces inside the braces

2017-06-17 23:30 UTC, jvanbruegge commented on src/eventHandlers/mousedown.ts
> +import { EventHandler, MouseOffset, SortableOptions} from '../definitions';
Please add a space inside the brace

2017-06-17 23:30 UTC, jvanbruegge commented on src/eventHandlers/mousedown.ts
> +export const mousedownHandler : EventHandler = (node, event, options: SortableOptions) => {
The type of options is already defined in `EventHandler`

2017-06-17 23:30 UTC, jvanbruegge commented on src/eventHandlers/mousedown.ts
> +    const mouseOffset = {
Please leave the type in

2017-06-17 23:30 UTC, jvanbruegge commented on src/eventHandlers/mousedown.ts
> +    const style = getGhostStyle(event, mouseOffset, item)
We are not reusing `style`, so no need to declare a var

2017-06-17 23:30 UTC, jvanbruegge commented on src/eventHandlers/mousemove.ts
> +    const style = updateGhostStyle(event, mouseOffset, ghost.elm as Element)
Same here

2017-06-17 23:30 UTC, jvanbruegge commented on src/helpers.ts
> +{
Trailing spaces

2017-06-17 23:30 UTC, jvanbruegge commented on src/helpers.ts
> +    const out = 'z-index: 5; margin: 0; pointer-events: none; position: absolute; ' +
no need to create var here

2017-06-17 23:30 UTC, jvanbruegge commented on src/helpers.ts
> +export function updateGhostStyle(event : any, mouseOffset : MouseOffset, ghost : Element) : string
Is this needed for TouchEvents? If so I would use a sum type

2017-06-17 23:30 UTC, jvanbruegge commented on src/helpers.ts
> +    const out = prevStyle.substring(0, prevStyle.indexOf(' top:')) + ' top: '
No var needed

2017-06-17 23:30 UTC, jvanbruegge commented on src/helpers.ts
> +
Please remove line

2017-06-17 23:30 UTC, jvanbruegge commented on src/makeSortable.ts
> +function augmentStartDistance(ev : any, startX: any, startY: any) : any {
Please add spaces before colons

2017-06-17 23:30 UTC, jvanbruegge commented on src/makeSortable.ts
> +function augmentStartDistance(ev : any, startX: any, startY: any) : any {
I'm not sure if we should modify the event. Have to think about this

2017-06-17 23:30 UTC, jvanbruegge commented on src/makeSortable.ts
> +    return !node.children || node.children.length > 1
Semicolon

2017-06-18 01:20 UTC, ntilwalli commented
Updated

2017-06-18 02:08 UTC, ntilwalli commented
Performance can get laggy on larger lists.  What can we do to improve perf a bit?

2017-07-03 22:30 UTC, jvanbruegge commented
I'm sorry that I forgot this PR.
In the current state I cannot merge this. Please split the PR in parts (one oer bug/feature) and please use tslint to check for linting errors

2017-07-08 22:32 UTC, ntilwalli commented
@jvanbruegge is it possible to avoid breaking this up into separate PRs?  There are a lot of bug fixes and unwinding all of them will take a while.  Some fixes are dependent on others...  Can we discuss the changes instead?  And work through them?

2017-08-10 16:24 UTC, jvanbruegge commented
I've resolved the merge conflict in #16 
But it seems like all examples stop working with this

2017-08-10 16:24 UTC, closed without merging